### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by costisz** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#115]
When I run the downloaded solution test as showed in the 5-th capter, Write an instrumentation test, I get this error:

java.lang.IllegalStateException: No compose hierarchies found in the app. Possible reasons include: (1) the Activity that calls setContent did not launch; (2) setContent was not called; (3) setContent was called before the ComposeTestRule ran. If setContent is called by the Activity, make sure the Activity is launched after the ComposeTestRule runs
at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:95)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNodes$ui_test_release(SemanticsNodeInteraction.kt:62)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:128)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
at androidx.compose.ui.test.TextActionsKt.getNodeAndFocus(TextActions.kt:104)
at androidx.compose.ui.test.TextActionsKt.getNodeAndFocus$default(TextActions.kt:101)
at androidx.compose.ui.test.TextActionsKt.performTextInput(TextActions.kt:93)
at androidx.compose.ui.test.TextActionsKt.performTextInput(TextActions.kt:40)
at com.example.tiptime.TipUITests.calculate_20_percent_tip(TipUITests.kt:43)

**Comment by android-dev-lxl** [comment]
@costisz 
We appreciate you bringing this issue to our attention. 
We have updated dependency versions, could you please try to run it again.
