### ISSUE TITLE
Local & Instrumentation testing: Locale issue with expectedTip value in USD

### ISSUE THREAD

**Issue by jincy-p-janardhanan** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#20]
When the locale of your region is not USD, then the local & instrumentation testing fails. I'm from India and I got the following error info in debugger for local testing.

```kotlin
expected:<[$ ]2.00> but was:<[₹ ]2.00>
Expected :$ 2.00
Actual   :₹ 2.00

org.junit.ComparisonFailure: expected:<[$ ]2.00> but was:<[₹ ]2.00>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.example.tiptime.TipCalculatorTests.calculate_20_percent_tip_no_roundup(TipCalculatorTests.kt:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

```

Moreover, simply copying the Rupee symbol (₹) will also not work, because the Indian locale currency is formatted with a NBSP character after the symbol instead of a space. Therefore, the safest option for testing is to use the same currency formatting for expected value with the help of Java number formatting packages.

I fixed my code by changing `val expectedTip = "$ 2.00"` with:
```kotlin
val expectedTip = NumberFormat.getCurrencyInstance().format(2.00)
```
This ensured the `expectedTip` value is always formatted in the current locale. The following import is also needed: 
```kotlin
import java.text.NumberFormat
```

Note: Similar changes needed in instrumentation testing also.

**Comment by v79** [comment]
In addition, the Instrumented Test in the next section runs on the emulator, which by default has the US Locale - and so the tip amount is presented as "$2.00". So the Unit Tests and Instrumented Tests have different actual values for the same calculation.

**Comment by divyanshdxn** [comment]
@jincy-p-janardhanan would you consider closing this issue? As it it already tracked https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/3, it would be good to have a single place where same issue is tracked. And yes, the solution you suggest I also think is correct.

**Comment by jincy-p-janardhanan** [comment]
Sure.

**Comment by osuleymanova** [comment]
Hello @gensart-ai,

Thank you for reaching out to us and sharing your feedback. Your fix suggested is the correct one.
The code snippet in the codelab is updated:

![Screenshot 2023-01-30 at 9 22 59 AM](https://user-images.githubusercontent.com/86437155/215555798-86edce7d-f1c9-49a8-b1e3-8715669a2de6.png)


Be sure that import java.text.NumberFormat is imported.
