### ISSUE TITLE
The test function should also use currency formatted string

### ISSUE THREAD

**Issue by divyanshdxn** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#38]
The test function should also use currency formated string like `NumberFormat.getCurrencyInstance().format(tip)`

The test fails for different locale with output,
```bash
expected:<[$]2.00> but was:<[₹ ]2.00>
Expected :$2.00
Actual   :₹ 2.00
<Click to see difference>

junit.framework.ComparisonFailure: expected:<[$]2.00> but was:<[₹ ]2.00>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.example.tiptime.TipCalculatorTests.calculate_20_percent_tip_no_roundup(TipCalculatorTest.kt:14)
	.......
```

From my Locale, the actual function picked up the Rupee symbol but the test had dollar symbol.

**Comment by divyanshdxn** [comment]
Sorry, I did created a copy of this issue https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/20
